### PR TITLE
BlogVault: Merge Automattic Code to the plugin

### PR DESCRIPTION
**Pull request by bv-shivamsharma**
# Changes 
1. The src content has been moved to a new folder named wpcom-migration
2. Files/Folder Changed
- wpcom-migration/admin/main_page.php
- wpcom-migration/assets
- wpcom-migratino/wp_admin.php

### CODE REVIEW

**Comment by bv-shivamsharma** [comment]
@markbiek, Can you please review this PR? I have moved the contents to a new folder name that matches the slug of the migration plugin and replaced the contents of 'admin 'and 'assets' folders.

Let me know if I'm missing something. Thanks

**Review by markbiek — APPROVED** [review]
This seems to be working properly!

I'll be updating the readme.txt later today as well.

**Comment by markbiek** [comment]
FYI, I updated the readme.txt in https://github.com/blogvault/wpcom-migration/pull/19

**Comment by bv-shivamsharma** [comment]
@markbiek Thanks a lot for reviewing the PR. Let me know when this can be merged.
Also, the initial iteration is now live on our servers and your team can use the generated plugin to test the migrations.

**Comment by markbiek** [comment]
Go ahead and merge.

**Pull request merged**
