### PR TITLE
Plugin Code Improvements

### PR DESCRIPTION
**Pull request by bv-shivamsharma**
Hi @markbiek, I have addressed the following issues.

https://github.com/blogvault/wpcom-migration/issues/20
https://github.com/blogvault/wpcom-migration/issues/21
https://github.com/blogvault/wpcom-migration/issues/22
https://github.com/blogvault/wpcom-migration/issues/23
https://github.com/blogvault/wpcom-migration/issues/24
https://github.com/blogvault/wpcom-migration/issues/25
https://github.com/blogvault/wpcom-migration/issues/26
https://github.com/blogvault/wpcom-migration/issues/29
https://github.com/blogvault/wpcom-migration/issues/30
https://github.com/blogvault/wpcom-migration/issues/33
https://github.com/blogvault/wpcom-migration/issues/34
https://github.com/blogvault/wpcom-migration/issues/35

The issues related to our app mentioned above have been fixed and deployed.

This PR contains changes related to the plugin, please have a look at the changes and let me know if there's any change that needs to be made.

Meanwhile, your team could run tests using this plugin with the latest code. 
[wpcom-migration.zip](https://github.com/user-attachments/files/16926658/wpcom-migration.zip)

P.S. I have used the dash icons for the migration key visibility token as I could not get the icon displayed on the image in the issue https://github.com/blogvault/wpcom-migration/issues/22. Please have a look and I'll make the changes that are needed. Thanks.

I missed the issue https://github.com/blogvault/wpcom-migration/issues/32 and will get that deployed in the next iteration.

Regarding the issues https://github.com/blogvault/wpcom-migration/issues/27,  https://github.com/blogvault/wpcom-migration/issues/28, and https://github.com/blogvault/wpcom-migration/issues/31, I'll discuss them with my team and will get back to you.

### CODE REVIEW

**Review by markbiek — APPROVED** [review]
This is looking good, thanks!

**Comment by markbiek** [comment]
@bv-shivamsharma Thanks for getting that first round of changes done so quickly!

Going forward, do we need to wait for you to provide a plugin `.zip` file or will it be OK to get the latest plugin code from this repository?

**Comment by bv-shivamsharma** [comment]
Update

Issues https://github.com/blogvault/wpcom-migration/issues/27, https://github.com/blogvault/wpcom-migration/issues/28 and https://github.com/blogvault/wpcom-migration/issues/32 have been addressed as well.

**Comment by bv-shivamsharma** [comment]
> Going forward, do we need to wait for you to provide a plugin `.zip` file or will it be OK to get the latest plugin code from this repository?

To avoid inconsistency you'd have to wait for us to provide you the plugin.

**Comment by markbiek** [comment]
Hi @bv-shivamsharma This is looking really good. There was one issue that didn't seem to be fixed and a couple of issues I haven't tested yet. 

I've closed every issue that I've verified and am going to merge this PR.

Please send us a new plugin `.zip` when it's ready.

**Comment by bv-shivamsharma** [comment]
Hi @markbiek You can use the above-mentioned `.zip` file as there were no plugin changes made in the second iteration.

**Pull request merged**
