### PR TITLE
Add the static main page

### PR DESCRIPTION
**Pull request by m1r0**
## Proposed Changes
* Add the main static page.
* Propose a scaffold for the static pages.
* Add some temporary code for loading the static pages in the context of WordPress.

## Screenshots

Desktop:

image

iPhone 12 (horizontal):

image

iPhone 12 (vertical):

image

## Testing Instructions

1. [Download](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fblogvault%2Fwpcom-migration%2Ftree%2Fadd%2Fstatic-main-page%2Fsrc) and install the plugin. You could use [jurassic.ninja](https://jurassic.ninja/) for a quick environment setup.
2. Go to `/wp-admin/admin.php?page=automattic&static=main`.
3. Compare the page to the [design](https://www.figma.com/design/c9jLiGBEqrxgEpHc8ccVFr/WP.com-migration-plugin-screen-designs?node-id=163-411&t=E27OyiNeJR3nqdoN-0). Having small differences should be fine, IMO.
4. Make sure it looks good on mobile and the different browsers.

### CODE REVIEW

**Comment by markbiek** [comment]
This is looking good!

What do you think about having a separate CSS file that defines a bunch of CSS variables (colors, fonts, common widths, etc).

**Comment by m1r0** [comment]
Good idea, Mark!

I've added a file for the variables and added the more obvious ones. I think we should continue updating that as we go, but do let me know if you think I missed something.

**Comment by m1r0** [comment]
There could be some copy updates related to p1723640302139239-slack-C07GG60B2AD but overall this should be ready for review. 🙂

**Review by markbiek — APPROVED** [review]
LGTM!

I like how everything is organized and it tested well on mobile and in desktop Chrome & Firefox.

**Comment by m1r0** [comment]
@fditrapani, could you give the mobile version a quick view? I'm not sure about the spacing and font-sizes. Also, please ignore the checkbox bug, it will be fixed in the next iteration. 🙂

**Comment by fditrapani** [comment]
Nice! This looks good from the screenshots but I can't get it to install locally. I'll connect with you on slack to get it working.

**Pull request merged**
